In [1]:
import numpy as np 
ar = np.random.randint(low=50,high=100,size=6)
print(ar)

[67 96 99 75 97 53]


In [2]:
ar_1 = np.arange(5,13)
print(ar_1)

[ 5  6  7  8  9 10 11 12]


In [3]:
feature = np.arange(6,21)
print(feature)
label= feature*3 + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [5]:
import random as random
noise = label + random.randint(2,10)
print(noise)

[27 30 33 36 39 42 45 48 51 54 57 60 63 66 69]


In [11]:
print(np.random.random([4])*4-2)

[-1.20467868 -0.84425067 -1.88194578  1.84236274]


In [6]:

noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[-0.036613    0.59503388  1.00300715 -0.28489958 -1.55509624  1.06480042
 -1.87174735  1.74869236 -0.72470957  1.13504782  1.87998332 -0.85550567
  1.90001966  1.57421872  1.34881238]
[21.963387   25.59503388 29.00300715 30.71510042 32.44490376 38.06480042
 38.12825265 44.74869236 45.27529043 50.13504782 53.87998332 54.14449433
 59.90001966 62.57421872 65.34881238]
